name: "RPL-2023-CICD Demo"
on:
  push:
    branches:
    - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Do python linter test check
      run: |
        sudo apt install python3-pip -y
        python -m pip install pylint
        pip install flask
        pylint app.py --disable=C0114,C0116
    - name: create folder for copying file
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: mkdir -p /home/rplcicd/13521104 
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        source: "app.py"
        target: "/home/rplcicd/13521104/"
    - name: kill existing flask app
      continue-on-error: true
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: pkill -f 21104
    - name: start flask app
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: cd /home/rplcicd/13521104 && screen -dmS flask-21104 python3 -m flask run --host=0.0.0.0 --port=21104 && ps -ef | grep 21104
