name: "RPL-2023-CICD Demo"

on:
  push:
    branches:
    - !main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Do python linter test check
      run: |
        sudo apt install python3-pip -y
        python -m pip install pylint
        pip install flask
        pylint app.py --disable=C0114,C0116
